GIT_TAG=$1
PROJECT_URL=$2
TOKEN=$3

echo "PROJECT_URL: ${PROJECT_URL}"
echo "GIT_TAG: ${GIT_TAG}"

regex='([0-9]+)\.([0-9]+)\.([0-9]+)?(.+)'
TERRAFORM_MODULE_VERSION=$(echo "$GIT_TAG"  | grep -Eio $regex)
echo "TERRAFORM_MODULE_VERSION: ${TERRAFORM_MODULE_VERSION}"

sed_string="s/-${TERRAFORM_MODULE_VERSION}//g"
TERRAFORM_MODULE_DIR=$(sed "$sed_string" <<<$GIT_TAG)
echo "TERRAFORM_MODULE_DIR: ${TERRAFORM_MODULE_DIR}"

IFS='/' read -r -a spitted <<<"${TERRAFORM_MODULE_DIR}"
TERRAFORM_MODULE_NAME="${spitted[-1]}"
echo "TERRAFORM_MODULE_NAME: ${TERRAFORM_MODULE_NAME}"

len=$(expr ${#spitted[@]} - 1)
TERRAFORM_MODULE_SYSTEM="${spitted[0]}"
for (( i=1; i<$len; i++ ))
do
  TERRAFORM_MODULE_SYSTEM="${TERRAFORM_MODULE_SYSTEM}-${spitted[$i]}"
done
echo "TERRAFORM_MODULE_SYSTEM: ${TERRAFORM_MODULE_SYSTEM}"

tar -cvzf ${TERRAFORM_MODULE_NAME}-${TERRAFORM_MODULE_SYSTEM}-${TERRAFORM_MODULE_VERSION}.tgz -C ${TERRAFORM_MODULE_DIR} --exclude=./.git .
curl --header "PRIVATE-TOKEN: ${TOKEN}" --upload-file ${TERRAFORM_MODULE_NAME}-${TERRAFORM_MODULE_SYSTEM}-${TERRAFORM_MODULE_VERSION}.tgz ${PROJECT_URL}/packages/terraform/modules/${TERRAFORM_MODULE_NAME}/${TERRAFORM_MODULE_SYSTEM}/${TERRAFORM_MODULE_VERSION}/file